// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipmentAPI.Models;

namespace ShipmentAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220523154657_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShipmentAPI.Models.Commodity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("ShipmentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ShipmentID");

                    b.ToTable("commodities");
                });

            modelBuilder.Entity("ShipmentAPI.Models.Shipment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Delivery_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Delivery_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Delivery_shipper_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_shipper_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Pickup_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pickup_point_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pickup_shipper_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pickup_shipper_phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("shipments");
                });

            modelBuilder.Entity("ShipmentAPI.Models.Commodity", b =>
                {
                    b.HasOne("ShipmentAPI.Models.Shipment", null)
                        .WithMany("Commodities")
                        .HasForeignKey("ShipmentID");
                });

            modelBuilder.Entity("ShipmentAPI.Models.Shipment", b =>
                {
                    b.Navigation("Commodities");
                });
#pragma warning restore 612, 618
        }
    }
}
